<script lang="ts">
  import * as ECharts from 'echarts';
  import { locale } from '$lib/i18n';
  import type { MissionInput, MissionResult } from '$core/types';
  import Chart from './Chart.svelte';
  import Icon from './Icon.svelte';
  import RotorCoverage from './RotorCoverage.svelte';

  export let result: MissionResult | null = null;
  export let input: MissionInput;
  $: en = $locale === 'en';
  const number = (value: number, digits = 1) => Number.isFinite(value) ? value.toFixed(digits) : '—';
  const labels = (name: 'hover' | 'cruise' | 'climb') => en ? ({ hover: 'Hover', cruise: 'Cruise', climb: 'Climb' }[name]) : ({ hover: 'هاور', cruise: 'کروز', climb: 'اوج‌گیری' }[name]);
  const warningLabels: Record<string, [string, string]> = {
    'battery-continuous-current': ['Battery continuous current', 'جریان دائم باتری'], 'battery-burst-current': ['Battery burst current', 'جریان لحظه‌ای باتری'], 'esc-continuous-current': ['ESC continuous current', 'جریان دائم ESC'], 'esc-burst-current': ['ESC burst current', 'جریان لحظه‌ای ESC'], 'motor-current': ['Motor current limit', 'جریان مجاز موتور'], 'motor-power': ['Motor power limit', 'توان مجاز موتور'], 'voltage-sag': ['Battery voltage sag', 'افت ولتاژ باتری'], 'insufficient-thrust': ['Insufficient thrust', 'رانش ناکافی'], 'propeller-clearance': ['Propeller clearance', 'فاصلهٔ آزاد ملخ'], 'curve-range': ['Operating point outside test curve', 'نقطهٔ کاری بیرون از منحنی تست'], 'missing-thermal-data': ['Motor thermal data missing', 'دادهٔ حرارتی موتور ناقص']
  };
  const text = (fa: string, english: string) => en ? english : fa;
  const axisStyle = { color: '#60769d', fontFamily: 'Inter, Vazir, sans-serif' };
  const baseGrid = { left: 46, right: 46, top: 34, bottom: 36 };
  $: curveOption = result ? ({ animationDuration: 600, animationEasing: 'cubicOut', grid: baseGrid, tooltip: { trigger: 'axis', confine: true }, legend: { top: 0, right: 0, textStyle: axisStyle }, xAxis: { type: 'category', data: result.points.map((p) => labels(p.name)), axisLabel: axisStyle, axisLine: { lineStyle: { color: '#a7bddc' } } }, yAxis: { type: 'value', name: 'N', nameTextStyle: axisStyle, axisLabel: axisStyle, splitLine: { lineStyle: { color: '#d7e4f5' } } }, series: [{ name: text('رانش', 'Thrust'), type: 'line', smooth: true, symbol: 'circle', symbolSize: 8, data: result.points.map((p) => p.thrustN), lineStyle: { width: 3, color: '#1167fa' }, itemStyle: { color: '#1167fa', borderColor: '#fff', borderWidth: 2 }, areaStyle: { color: 'rgba(17,103,250,.12)' } }] }) as ECharts.EChartsOption : null;
  $: currentOption = result ? ({ animationDuration: 680, animationEasing: 'cubicOut', grid: baseGrid, tooltip: { trigger: 'axis', confine: true }, legend: { top: 0, right: 0, textStyle: axisStyle }, xAxis: { type: 'category', data: result.points.map((p) => labels(p.name)), axisLabel: axisStyle, axisLine: { lineStyle: { color: '#a7bddc' } } }, yAxis: [{ type: 'value', name: 'A', axisLabel: axisStyle, splitLine: { lineStyle: { color: '#d7e4f5' } } }, { type: 'value', name: 'W', axisLabel: axisStyle, splitLine: { show: false } }], series: [{ name: text('جریان', 'Current'), type: 'line', smooth: true, data: result.points.map((p) => p.totalCurrentA), lineStyle: { width: 2.5, color: '#18b879' }, itemStyle: { color: '#18b879' } }, { name: text('توان', 'Power'), type: 'line', yAxisIndex: 1, smooth: true, data: result.points.map((p) => p.totalPowerW), lineStyle: { width: 2.5, color: '#f28b22' }, itemStyle: { color: '#f28b22' } }] }) as ECharts.EChartsOption : null;
  $: speedOption = result ? ({ animationDuration: 680, animationEasing: 'cubicOut', grid: baseGrid, tooltip: { trigger: 'axis', confine: true }, legend: { top: 0, right: 0, textStyle: axisStyle }, xAxis: { type: 'category', data: result.speedProfile.map((p) => number(p.speedMps)), name: 'm/s', nameTextStyle: axisStyle, axisLabel: axisStyle, axisLine: { lineStyle: { color: '#a7bddc' } } }, yAxis: [{ type: 'value', name: 'min', axisLabel: axisStyle, splitLine: { lineStyle: { color: '#d7e4f5' } } }, { type: 'value', name: 'km', axisLabel: axisStyle, splitLine: { show: false } }], series: [{ name: text('زمان پرواز', 'Flight time'), type: 'line', smooth: true, data: result.speedProfile.map((p) => p.flightTimeMin), lineStyle: { width: 2.5, color: '#1167fa' }, itemStyle: { color: '#1167fa' } }, { name: text('برد', 'Range'), type: 'line', yAxisIndex: 1, smooth: true, data: result.speedProfile.map((p) => p.rangeKm), lineStyle: { width: 2.5, color: '#8d63e8' }, itemStyle: { color: '#8d63e8' } }] }) as ECharts.EChartsOption : null;
  $: altitudeOption = result ? ({ animationDuration: 700, animationEasing: 'cubicOut', grid: baseGrid, tooltip: { trigger: 'axis', confine: true }, legend: { top: 0, right: 0, textStyle: axisStyle }, xAxis: { type: 'category', data: result.altitudeProfile.map((p) => Math.round(p.altitudeM)), name: 'm', nameTextStyle: axisStyle, axisLabel: axisStyle, axisLine: { lineStyle: { color: '#a7bddc' } } }, yAxis: [{ type: 'value', name: 'N', axisLabel: axisStyle, splitLine: { lineStyle: { color: '#d7e4f5' } } }, { type: 'value', name: '%', axisLabel: axisStyle, splitLine: { show: false } }], series: [{ name: text('رانش موجود', 'Available thrust'), type: 'line', smooth: true, data: result.altitudeProfile.map((p) => p.availableThrustN), lineStyle: { width: 2.5, color: '#18b879' }, itemStyle: { color: '#18b879' } }, { name: text('حاشیهٔ رانش', 'Thrust margin'), type: 'line', yAxisIndex: 1, smooth: true, data: result.altitudeProfile.map((p) => p.thrustMargin * 100), lineStyle: { width: 2.5, color: '#f28b22' }, itemStyle: { color: '#f28b22' } }] }) as ECharts.EChartsOption : null;
  $: powerOption = result ? ({ animationDuration: 620, animationEasing: 'cubicOut', tooltip: { trigger: 'item', formatter: (item: any) => `${item.name}: ${number(Number(item.value), 0)} W` }, legend: { bottom: 0, left: 'center', textStyle: axisStyle }, series: [{ type: 'pie', radius: ['45%', '70%'], center: ['50%', '43%'], itemStyle: { borderColor: '#fff', borderWidth: 3 }, label: { show: true, formatter: '{d}%', color: '#141c56', fontFamily: 'Inter, Vazir, sans-serif', fontWeight: 700 }, data: [{ value: result.power.propulsiveW, name: text('پروانه', 'Propeller'), itemStyle: { color: '#1167fa' } }, { value: result.power.motorLossW, name: text('تلفات موتور', 'Motor loss'), itemStyle: { color: '#f28b22' } }, { value: result.power.escLossW, name: 'ESC loss', itemStyle: { color: '#18b879' } }, { value: result.power.batteryLossW, name: text('تلفات باتری', 'Battery loss'), itemStyle: { color: '#8d63e8' } }] }] }) as ECharts.EChartsOption : null;
</script>

{#if result}
  <section class="results" aria-labelledby="result-title">
    <div class="result-heading"><div><span class="kicker">{text('خلاصهٔ مهندسی', 'Engineering summary')}</span><h2 id="result-title">{text('نتیجهٔ پرواز', 'Flight result')}</h2></div><span class:danger={result.warnings.some((w) => w.severity === 'critical')} class="state">{result.warnings.some((w) => w.severity === 'critical') ? text('نیازمند بررسی', 'Review required') : text('قابل قبول', 'Within limits')}</span></div>
    <div class="metrics">
      <article><span class="metric__icon metric__icon--green"><Icon name="clock" size={22} /></span><div><small>{text('زمان قابل استفاده', 'Usable flight time')}</small><strong class="data">{number(result.flightTimeMin)} <em>min</em></strong></div></article>
      <article><span class="metric__icon metric__icon--blue"><Icon name="pin" size={22} /></span><div><small>{text('برد برآوردی', 'Estimated range')}</small><strong class="data">{number(result.rangeKm)} <em>km</em></strong></div></article>
      <article><span class="metric__icon metric__icon--orange"><Icon name="rocket" size={22} /></span><div><small>{text('نسبت رانش به وزن', 'Thrust-to-weight')}</small><strong class="data">{number(result.thrustToWeight)} <em>: 1</em></strong></div></article>
      <article><span class="metric__icon metric__icon--yellow"><Icon name="bolt" size={22} /></span><div><small>{text('توان هاور', 'Hover power')}</small><strong class="data">{number(result.totalPowerW, 0)} <em>W</em></strong></div></article>
      <article><span class="metric__icon metric__icon--purple"><Icon name="ceiling" size={22} /></span><div><small>{text('سقف پیشنهادی', 'Suggested ceiling')}</small><strong class="data">{result.ceilingM == null ? '—' : number(result.ceilingM, 0)} <em>{result.ceilingM == null ? '' : 'm'}</em></strong></div></article>
      <article><span class="metric__icon metric__icon--cyan"><Icon name="bolt" size={22} /></span><div><small>{text('ولتاژ زیر بار', 'Loaded voltage')}</small><strong class="data">{number(result.loadedVoltageV, 1)} <em>V</em></strong></div></article>
    </div>
    <div class="fact-strip"><span>{text('جرم برخاست', 'Takeoff mass')} <b class="data">{number(result.takeoffMassKg, 2)} kg</b></span><span>{text('چگالی هوا', 'Air density')} <b class="data">{number(result.airDensityKgM3, 3)} kg/m³</b></span><span>{text('رانش ویژه', 'Specific thrust')} <b class="data">{number(result.specificThrustGPerW, 2)} g/W</b></span><span>{text('دمای موتور', 'Motor temperature')} <b class="data">{result.motorTemperatureC == null ? '—' : `${number(result.motorTemperatureC, 0)} °C`}</b></span></div>
    <div class="chart-grid">
      <article><div class="chart-head"><h3>{text('رانش در نقاط کاری', 'Thrust by operating point')}</h3><span class="data">N</span></div>{#if curveOption}<Chart option={curveOption} ariaLabel={text('نمودار رانش نقاط کاری', 'Operating-point thrust chart')} />{/if}</article>
      <article><div class="chart-head"><h3>{text('جریان و توان', 'Current and power')}</h3><span class="data">A · W</span></div>{#if currentOption}<Chart option={currentOption} ariaLabel={text('نمودار جریان و توان', 'Current and power chart')} />{/if}</article>
      <article><div class="chart-head"><h3>{text('زمان و برد نسبت به سرعت', 'Time and range by speed')}</h3><span class="data">min · km</span></div>{#if speedOption}<Chart option={speedOption} ariaLabel={text('نمودار زمان و برد نسبت به سرعت', 'Speed versus time and range chart')} />{/if}</article>
      <article><div class="chart-head"><h3>{text('رانش و حاشیه نسبت به ارتفاع', 'Thrust and margin by altitude')}</h3><span class="data">N · %</span></div>{#if altitudeOption}<Chart option={altitudeOption} ariaLabel={text('نمودار رانش و حاشیه نسبت به ارتفاع', 'Altitude thrust and margin chart')} />{/if}</article>
      <article class="chart-grid__power"><div class="chart-head"><h3>{text('توزیع توان و تلفات', 'Power and loss breakdown')}</h3><span class="data">{number(result.totalPowerW, 0)} W</span></div>{#if powerOption}<Chart option={powerOption} ariaLabel={text('نمودار توزیع توان', 'Power breakdown chart')} />{/if}</article>
    </div>
    <article class="coverage"><div class="chart-head"><h3>{text('پوشش و فاصلهٔ روتورها', 'Rotor layout and clearance')}</h3><span class="data">{number(result.thrustMargin * 100, 0)}%</span></div><RotorCoverage rotorCount={input.airframe.rotorCount} frameSizeM={input.airframe.frameSizeM} propellerDiameterM={input.propeller.diameterM} layout={input.airframe.layout} /></article>
    <article class="warnings"><div class="chart-head"><h3>{text('هشدارها', 'Checks')}</h3><span class="data">{result.warnings.length}</span></div>{#if result.warnings.length === 0}<p>{text('موردی برای بررسی نیست.', 'No checks need attention.')}</p>{:else}<ul>{#each result.warnings as warning}<li class:critical={warning.severity === 'critical'}><b>{warning.severity === 'critical' ? '!' : '·'}</b><span>{warningLabels[warning.code]?.[en ? 0 : 1] ?? text('نیازمند بررسی', 'Review required')}</span></li>{/each}</ul>{/if}</article>
  </section>
{/if}

<style>
  .results { display:grid; gap:14px; }.result-heading,.chart-head { display:flex; align-items:baseline; justify-content:space-between; gap:12px; }.kicker { color:var(--muted); font-size:12px; }.result-heading h2 { margin:3px 0 0; font-size:27px; letter-spacing:-.04em; }.state { border-radius:999px; background:color-mix(in oklch,var(--green) 12%,transparent); color:var(--green); padding:5px 11px; font-size:12px; }.state.danger { background:color-mix(in oklch,var(--danger) 12%,transparent); color:var(--danger); }
  .metrics { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:10px; }.metrics article { display:flex; align-items:center; gap:11px; min-width:0; border:1px solid var(--line); border-radius:13px; background:var(--surface); padding:12px; box-shadow:var(--shadow-soft); }.metric__icon { display:grid; flex:0 0 40px; width:40px; height:40px; place-items:center; border-radius:12px; }.metric__icon--green { background:color-mix(in oklch,var(--green) 14%,transparent); color:var(--green); }.metric__icon--blue { background:var(--blue-soft); color:var(--blue); }.metric__icon--orange { background:var(--orange-soft); color:var(--orange); }.metric__icon--yellow { background:color-mix(in oklch,#d9a400 15%,transparent); color:#b28200; }.metric__icon--purple { background:color-mix(in oklch,#8d63e8 14%,transparent); color:#8d63e8; }.metric__icon--cyan { background:color-mix(in oklch,#159fb4 14%,transparent); color:#159fb4; }.metrics small { display:block; color:var(--muted); font-size:11px; }.metrics strong { display:block; margin-top:2px; font-size:20px; }.metrics em { color:var(--muted); font-size:11px; font-style:normal; font-weight:500; }.fact-strip { display:flex; flex-wrap:wrap; gap:8px 18px; border-block:1px solid var(--line); padding:11px 2px; color:var(--muted); font-size:12px; }.fact-strip b { color:var(--ink); margin-inline-start:4px; }
  .chart-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; }.chart-grid>article,.coverage,.warnings { min-width:0; border:1px solid var(--line); border-radius:var(--radius); background:var(--surface); padding:15px; box-shadow:var(--shadow-soft); }.chart-grid__power { grid-column:1/-1; }.chart-head h3 { margin:0; font-size:14px; }.chart-head>span { color:var(--muted); font-size:12px; }.warnings p { margin:10px 0 0; color:var(--muted); font-size:13px; }.warnings ul { display:grid; gap:8px; margin:12px 0 0; padding:0; list-style:none; color:var(--orange); font-size:13px; }.warnings li { display:flex; gap:8px; align-items:center; }.warnings li.critical { color:var(--danger); }.warnings li b { display:grid; width:20px; height:20px; place-items:center; border-radius:50%; background:currentColor; color:var(--surface); font-size:12px; }.coverage :global(.coverage) { margin-top:12px; }
  @media (max-width:900px) { .metrics { grid-template-columns:repeat(2,minmax(0,1fr)); } } @media (max-width:720px) { .chart-grid { grid-template-columns:minmax(0,1fr); }.chart-grid__power { grid-column:auto; }.fact-strip { gap:8px 12px; }.metrics article { padding:11px; } } @media (max-width:420px) { .metrics { grid-template-columns:minmax(0,1fr); }.result-heading h2 { font-size:23px; }.state { font-size:11px; padding:4px 8px; } }
</style>
