<script lang="ts">
  import { onMount } from 'svelte';
  import Icon from './Icon.svelte';
  import { locale } from '$lib/i18n';
  export let theme: 'light' | 'dark' = 'light';
  export let onThemeChange: (theme: 'light' | 'dark') => void;
  export let motionEnabled = true;
  export let onMotionChange: (enabled: boolean) => void = () => {};
  let units: 'metric' | 'imperial' = 'metric';
  let language: 'fa' | 'en' = 'fa';
  $: ui = $locale === 'en' ? {
    title: 'Settings', heading: 'App settings', intro: 'Tune units and display behavior.', display: 'Calculation display', displayHint: 'Units shown in forms and results.', units: 'Unit system', metric: 'Metric (SI)', imperial: 'Imperial', language: 'Language', appearance: 'Appearance', appearanceHint: 'Color and contrast for the workspace.', light: 'Light', dark: 'Dark', device: 'Stored on this device.', motion: 'Interface motion', motionHint: 'Page and sheet transitions.', enabled: 'Enabled', disabled: 'Disabled', data: 'Data sources', dataHint: 'Component and aircraft records are bundled for offline use.', components: 'Base components', aircraft: 'Aircraft profiles', sources: 'Source groups'
  } : {
    title: 'تنظیمات', heading: 'تنظیمات برنامه', intro: 'واحدها و رفتار نمایش را تنظیم کنید.', display: 'نمایش محاسبات', displayHint: 'واحدهایی که در فرم و نتیجه دیده می‌شوند.', units: 'سیستم واحد', metric: 'متریک (SI)', imperial: 'امپریال', language: 'زبان', appearance: 'ظاهر برنامه', appearanceHint: 'رنگ و کنتراست محیط کار.', light: 'روشن', dark: 'تیره', device: 'تنظیمات در همین دستگاه ذخیره می‌شود.', motion: 'حرکت رابط', motionHint: 'ورود صفحه‌ها و بازشدن پنجره‌ها.', enabled: 'فعال', disabled: 'خاموش', data: 'منابع داده', dataHint: 'فهرست قطعات و مدل‌های پرنده به‌صورت آفلاین همراه برنامه نگه‌داری می‌شود.', components: 'قطعات پایه', aircraft: 'پروفایل پرنده', sources: 'منابع خام'
  };
  onMount(() => {
    const storedUnits = localStorage.getItem('open-ecalc.units');
    const storedLanguage = localStorage.getItem('open-ecalc.language');
    if (storedUnits === 'metric' || storedUnits === 'imperial') units = storedUnits;
    const detected: 'fa' | 'en' = navigator.languages?.some((item) => item.toLowerCase().startsWith('fa')) ? 'fa' : 'en';
    language = storedLanguage === 'fa' || storedLanguage === 'en' ? storedLanguage : detected;
    applyLanguage(language);
  });
  function persist() { localStorage.setItem('open-ecalc.units', units); }
  function applyLanguage(next: 'fa' | 'en') {
    language = next;
    localStorage.setItem('open-ecalc.language', next);
    localStorage.setItem('open-ecalc.locale', next);
    locale.set(next);
    document.documentElement.lang = next;
    document.documentElement.dir = next === 'fa' ? 'rtl' : 'ltr';
    window.dispatchEvent(new CustomEvent('open-ecalc-languagechange', { detail: next }));
  }
</script>

<section class="settings-page" aria-labelledby="settings-title">
  <header class="settings-head"><div><span class="eyebrow">{ui.title}</span><h1 id="settings-title">{ui.heading}</h1><p>{ui.intro}</p></div></header>
  <div class="settings-grid">
    <section class="settings-card"><div class="settings-card__title"><Icon name="sliders" size={23} /><div><h2>{ui.display}</h2><p>{ui.displayHint}</p></div></div><label><span>{ui.units}</span><select bind:value={units} on:change={persist}><option value="metric">{ui.metric}</option><option value="imperial">{ui.imperial}</option></select></label><label><span>{ui.language}</span><select value={language} on:change={(event) => applyLanguage((event.currentTarget as HTMLSelectElement).value as 'fa' | 'en')}><option value="fa">فارسی</option><option value="en">English</option></select></label></section>
    <section class="settings-card"><div class="settings-card__title"><Icon name={theme === 'dark' ? 'moon' : 'sun'} size={23} /><div><h2>{ui.appearance}</h2><p>{ui.appearanceHint}</p></div></div><label class="theme-choice"><span class="theme-swatch" class:dark={theme === 'dark'}></span><span>{theme === 'light' ? ui.light : ui.dark}</span><input class="theme-checkbox" type="checkbox" checked={theme === 'dark'} on:change={() => onThemeChange(theme === 'light' ? 'dark' : 'light')} /><span class="theme-switch" aria-hidden="true"><i></i></span></label><p class="settings-note">{ui.device}</p></section>
    <section class="settings-card"><div class="settings-card__title"><Icon name="sliders" size={23} /><div><h2>{ui.motion}</h2><p>{ui.motionHint}</p></div></div><label class="theme-choice"><span class="motion-swatch"><Icon name="spark" size={17} /></span><span>{motionEnabled ? ui.enabled : ui.disabled}</span><input class="theme-checkbox" type="checkbox" checked={motionEnabled} on:change={() => onMotionChange(!motionEnabled)} /><span class="theme-switch" aria-hidden="true"><i></i></span></label></section>
    <section class="settings-card settings-card--wide"><div class="settings-card__title"><Icon name="components" size={23} /><div><h2>{ui.data}</h2><p>{ui.dataHint}</p></div></div><div class="data-row"><span>{ui.components}</span><strong class="data">۸</strong></div><div class="data-row"><span>{ui.aircraft}</span><strong class="data">۱۵۹</strong></div><div class="data-row"><span>{ui.sources}</span><strong class="data">۵</strong></div></section>
  </div>
</section>

<style>
  .settings-page { display: grid; gap: 24px; }.settings-head { display: flex; align-items: end; justify-content: space-between; gap: 20px; }.eyebrow { color: var(--blue); font-size: 13px; }.settings-head h1 { margin: 5px 0 0; font-size: clamp(28px, 3vw, 42px); letter-spacing: -0.05em; }.settings-head p { margin: 6px 0 0; color: var(--muted); font-size: 13px; }.settings-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }.settings-card { display: grid; align-content: start; gap: 18px; border: 1px solid var(--line); border-radius: var(--radius); background: var(--surface); padding: 22px; box-shadow: var(--shadow-soft); }.settings-card--wide { grid-column: 1 / -1; }.settings-card__title { display: flex; align-items: flex-start; gap: 12px; }.settings-card__title :global(svg) { color: var(--blue); }.settings-card h2 { margin: 0; font-size: 18px; }.settings-card p { margin: 3px 0 0; color: var(--muted); font-size: 12px; }.settings-card label { display: grid; gap: 7px; color: var(--ink-soft); font-size: 13px; }.settings-card select { min-height: 48px; border: 1px solid var(--line); border-radius: 10px; background: var(--paper); color: var(--ink); padding-inline: 12px; }.theme-choice { display: flex !important; flex-direction: row; align-items: center; gap: 10px; min-height: 52px; border: 1px solid var(--line); border-radius: 11px; background: var(--paper); color: var(--ink); padding-inline: 12px; text-align: start; cursor: pointer; }.theme-switch { position: relative; width: 44px; height: 25px; margin-inline-start: auto; border-radius: 999px; background: var(--line); transition: background-color var(--fast) var(--ease); }.theme-switch i { position: absolute; top: 3px; inset-inline-start: 3px; width: 19px; height: 19px; border-radius: 50%; background: var(--surface); box-shadow: 0 2px 5px rgba(20, 23, 26, .18); transition: transform var(--fast) var(--ease); }.theme-choice:has(.theme-checkbox:checked) .theme-switch { background: var(--blue); }.theme-choice:has(.theme-checkbox:checked) .theme-switch i { transform: translateX(19px); }.theme-checkbox { position: absolute; width: 1px; height: 1px; opacity: 0; }.theme-choice:focus-within { border-color: var(--blue); box-shadow: 0 0 0 3px color-mix(in srgb, var(--blue) 16%, transparent); }.theme-swatch { width: 28px; height: 28px; border-radius: 9px; background: var(--paper); box-shadow: inset 0 0 0 1px var(--line); }.theme-swatch.dark { background: #101a35; box-shadow: inset 0 0 0 1px #263967; }.settings-note { font-size: 12px; }.data-row { display: flex; align-items: center; justify-content: space-between; border-top: 1px solid var(--line); padding-top: 11px; color: var(--ink-soft); }.data-row strong { color: var(--blue); }
  .settings-page { display: grid; gap: 24px; }.settings-head { display: flex; align-items: end; justify-content: space-between; gap: 20px; }.eyebrow { color: var(--blue); font-size: 13px; }.settings-head h1 { margin: 5px 0 0; font-size: clamp(28px, 3vw, 42px); letter-spacing: -0.05em; }.settings-head p { margin: 6px 0 0; color: var(--muted); font-size: 13px; }.settings-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }.settings-card { display: grid; align-content: start; gap: 18px; border: 1px solid var(--line); border-radius: var(--radius); background: var(--surface); padding: 22px; box-shadow: var(--shadow-soft); }.settings-card--wide { grid-column: 1 / -1; }.settings-card__title { display: flex; align-items: flex-start; gap: 12px; }.settings-card__title :global(svg) { color: var(--blue); }.settings-card h2 { margin: 0; font-size: 18px; }.settings-card p { margin: 3px 0 0; color: var(--muted); font-size: 12px; }.settings-card label { display: grid; gap: 7px; color: var(--ink-soft); font-size: 13px; }.settings-card select { min-height: 48px; border: 1px solid var(--line); border-radius: 10px; background: var(--paper); color: var(--ink); padding-inline: 12px; }.theme-choice { display: flex !important; flex-direction: row; align-items: center; gap: 10px; min-height: 52px; border: 1px solid var(--line); border-radius: 11px; background: var(--paper); color: var(--ink); padding-inline: 12px; text-align: start; cursor: pointer; }.theme-switch { position: relative; width: 44px; height: 25px; margin-inline-start: auto; border-radius: 999px; background: var(--line); transition: background-color var(--fast) var(--ease); }.theme-switch i { position: absolute; top: 3px; inset-inline-start: 3px; width: 19px; height: 19px; border-radius: 50%; background: var(--surface); box-shadow: 0 2px 5px rgba(20, 23, 26, .18); transition: transform var(--fast) var(--ease); }.theme-choice:has(.theme-checkbox:checked) .theme-switch { background: var(--blue); }.theme-choice:has(.theme-checkbox:checked) .theme-switch i { transform: translateX(19px); }.theme-checkbox { position: absolute; width: 1px; height: 1px; opacity: 0; }.theme-choice:focus-within { border-color: var(--blue); box-shadow: 0 0 0 3px color-mix(in srgb, var(--blue) 16%, transparent); }.theme-swatch, .motion-swatch { display: grid; width: 28px; height: 28px; place-items: center; border-radius: 9px; background: var(--paper); box-shadow: inset 0 0 0 1px var(--line); }.theme-swatch.dark { background: #101a35; box-shadow: inset 0 0 0 1px #263967; }.motion-swatch { color: var(--blue); }.settings-note { font-size: 12px; }.data-row { display: flex; align-items: center; justify-content: space-between; border-top: 1px solid var(--line); padding-top: 11px; color: var(--ink-soft); }.data-row strong { color: var(--blue); }
  @media (max-width: 640px) { .settings-head { align-items: start; }.settings-grid { grid-template-columns: minmax(0, 1fr); }.settings-card--wide { grid-column: auto; } }
</style>
